"""update_jsonb_server_default

Revision ID: 0a74bbcc6a16
Revises: 4cb637fed6f4
Create Date: 2026-07-31 17:31:45.266125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a74bbcc6a16'
down_revision: Union[str, Sequence[str], None] = '4cb637fed6f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
