"""correct created_at field in space

Revision ID: 68f02275306b
Revises: d2ca23d06efd
Create Date: 2026-08-17 16:59:14.264246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = '68f02275306b'
down_revision: Union[str, Sequence[str], None] = 'd2ca23d06efd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('node_id', sa.String(length=255), nullable=True))
    op.add_column('document_chunks', sa.Column('text', sa.Text(), nullable=False))
    op.add_column('document_chunks', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=3072), nullable=False))
    op.add_column('document_chunks', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    op.create_index(op.f('ix_document_chunks_node_id'), 'document_chunks', ['node_id'], unique=False)
    op.drop_column('document_chunks', 'embeddings')
    op.drop_column('document_chunks', 'content')
    op.add_column('space', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('space', 'create_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('space', sa.Column('create_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('space', 'created_at')
    op.add_column('document_chunks', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('document_chunks', sa.Column('embeddings', pgvector.sqlalchemy.vector.VECTOR(dim=3072), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_document_chunks_node_id'), table_name='document_chunks')
    op.drop_column('document_chunks', 'metadata')
    op.drop_column('document_chunks', 'embedding')
    op.drop_column('document_chunks', 'text')
    op.drop_column('document_chunks', 'node_id')
    # ### end Alembic commands ###
