"""add upload_status to space model

Revision ID: b5fd7ec8f197
Revises: ca913469f0f8
Create Date: 2026-08-19 15:57:16.189197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'b5fd7ec8f197'
down_revision: Union[str, Sequence[str], None] = 'ca913469f0f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('space', sa.Column('upload_status', sa.String(length=50), server_default='chat', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('space', 'upload_status')
    # ### end Alembic commands ###
