"""change tool_type field in space model

Revision ID: ca913469f0f8
Revises: 68f02275306b
Create Date: 2026-08-18 16:10:20.293414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'ca913469f0f8'
down_revision: Union[str, Sequence[str], None] = '68f02275306b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_space_tool_type'), table_name='space')
    op.alter_column('space', 'tool_type', new_column_name='tool')
    op.create_index(op.f('ix_space_tool'), 'space', ['tool'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_space_tool'), table_name='space')
    op.alter_column('space', 'tool', new_column_name='tool_type')
    op.create_index(op.f('ix_space_tool_type'), 'space', ['tool_type'], unique=False)
    # ### end Alembic commands ###
