"""add_thread_id_to_space

Revision ID: d2ca23d06efd
Revises: 0a74bbcc6a16
Create Date: 2026-07-31 19:45:14.416652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2ca23d06efd'
down_revision: Union[str, Sequence[str], None] = '0a74bbcc6a16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('space', sa.Column('thread_id', sa.UUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('space', 'thread_id')
    # ### end Alembic commands ###
